### ISSUE TITLE
Warning: max(): array must containt at least one element

### ISSUE THREAD

**Issue by fastlone** [jung3o/Many-New-Posts#3]
Warning reported on Polish MyBB support website.
![error](https://cloud.githubusercontent.com/assets/10711342/5903127/2fcc6132-a580-11e4-8ff6-f4da2a66f5b8.jpg)

I'd change these lines:
$userlastview = max($userlastview);
  $userlastview_forum = max($userlastview_forum);
to these
$userlastview = (count($userlastview) > 0) ? max($userlastview) : 0;
  $userlastview_forum = (count($userlastview_forum) > 0) ? max($userlastview_forum) : 0;

**Comment by jung3o** [comment]
Can you do a pull request and I'll accept it? I cant do it right now sorry.

**Comment by jung3o** [comment]
#4
